name: ci

on:
  push:
    branches:
      - dev
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@16
        with:
          config: .markdownlint-cli2.jsonc
          globs: "**/*.md"

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          conda-solver: libmamba
          environment-file: build_env.yml
          activate-environment: build

      - name: Build pages
        run: |
          conda activate build
          mkdocs gh-deploy --force --strict
